apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-app
        image: lehuy222/calculator-app:5.1p
        ports:
        - containerPort: 3000   
