apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
spec:
  type: NodePort
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 3000          # External port 
      targetPort: 3000    # Container port 
      nodePort: 30007     
